### ISSUE TITLE
Uncaught TypeError: t.test is not a function

### ISSUE THREAD

**Issue by aboutsam** [elbywan/yett#30]
Implemented in my page. The blocking function work like a charm but i get some TypeErrors

```
Uncaught TypeError: t.test is not a function
    at yett:1
    at Array.every (<anonymous>)
    at o (yett:1)
    at r (yett:1)
    at MutationObserver.<anonymous> (yett:1)Uncaught TypeError: t.test is not a function
```

**Comment by elbywan** [comment]
Hi @aboutsam,

> i get some TypeErrors

Can you please check that the `YETT_WHITELIST` or `YETT_BLACKLIST` arrays only contain [**RegExp**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) instances?

**Comment by aboutsam** [comment]
@elbywan yes, i forgot to preg_match my url before i pass into RegExp.

my url looks like test/test.js

first i preg_match via php

`/test\/\test\.js/`

and than i pass the string into my RegExp Js Instance

`new RegExp(`/test\/\test\.js/`)`
