### ISSUE TITLE
question about ecommerce 

### ISSUE THREAD

**Issue by d2flint** [elbywan/yett#41]
Wondering if this will work to block ecommerce sites from inserting unwanted script? I know little to nothing about coding, but I have a small online business and it drives me crazy that my platform lies to everyone and  hides a bunch of code behind hidden files. I was able to identify what file my platform uses to inject the code, I spoke with them and of course they refuse to let me delete it or even access the file. 

The unwanted scripts are found in a liquid file called "{{ content_for_header }}". Is there a way I can use your code to block this from executing? I've been trying to solve this for months, you are likely my last hope lol Thanks for any held you can offer!

**Comment by elbywan** [comment]
Hey @d2flint 👋,

> The unwanted scripts are found in a liquid file called "{{ content_for_header }}". Is there a way I can use your code to block this from executing?

I assume that if you find the url/domain of the unwanted scripts and have a way to inject `yett` and call it to block the scripts in the header **before** they get injected then it should work.

> Thanks for any held you can offer!

I'm sorry this is the best I can do, hoping this will help 🤞

**Comment by d2flint** [comment]
Awesome! I think I almost got it. I only get one error that says "uncaught
syntax error: unexpected string". It's found right at the BOLD language
below. Any idea what I did wrong?

<script>
const createElementBackup = document.createElement
document.createElement = function(...args) {
    if(args[0].toLowerCase() !== 'script')
        return createElementBackup.bind(document)(...args)

    const scriptElt = createElementBackup.bind(document)(...args)

    const originalSetAttribute = scriptElt.setAttribute.bind(scriptElt)

  *  Object.'script'(scriptElt, {*

      'src': {
        get() {
            return scriptElt.getAttribute('src')
        },
        set(value) {
            if(needsToBeBlacklisted(value, scriptElt.type)) {
                originalSetAttribute('type', 'javascript/blocked')
            }
            originalSetAttribute('src', value)
            return true
        }
    },
    'type': {
        set(value) {
            const typeValue =
                needsToBeBlacklisted(scriptElt.src, scriptElt.type) ?
                    'javascript/blocked' :
                value
            originalSetAttribute('type', typeValue)
            return true
        }
    }
})

  scriptElt.setAttribute = function(name, value) {
    if(name === 'type' || name === 'src')
        scriptElt[name] = value
    else
        HTMLScriptElement.protytope.setAttribute.call(scriptElt, name,
value)
}
    return scriptElt
}
  </script>
