### ISSUE TITLE
not working "https://my-blacklisted-domain.com/file.js"

### ISSUE THREAD

**Issue by devluchoc** [elbywan/yett#43]
Hi!
We are using the lock. But we noticed that it stopped working, when verifying what happened when we entered the domain "https://my-blacklisted-domain.com/file.js" it does not allow to throw "DNS_PROBE_FINISHED_NXDOMAIN". Is there a way to do this without using "https://my-blacklisted-domain.com/file.js"? Where can we find the file "file.js"?
Thanks.

**Comment by elbywan** [comment]
Hey @devluchoc,

I assume you copy pasted the `https://my-blacklisted-domain.com/file.js` source from the readme here: https://github.com/elbywan/yett#small-example

```html
<script>
      window.YETT_BLACKLIST = [
        /my-blacklisted-domain/,
      ]
      // Or a whitelist
      window.YETT_WHITELIST = [
        /my-whitelisted-domain/,
      ]
    </script>
    <!-- 2) Include Yett -->
    <script src="https://unpkg.com/yett"></script>
    <!-- If you target only modern browsers (!= IE) you should use the following version. It is way smaller! -->
    <!-- <script src="https://unpkg.com/yett/dist/yett.min.modern.js"></script -->
    <!-- 3) Profit! -->
    <!-- This script is blocked -->
    <script src="https://my-blacklisted-domain.com/file.js"></script>
```

This domain was made for the purpose of the example and was not meant to be taken literally.

You should replace `https://my-blacklisted-domain.com/file.js` with a real URL of the script you want to block, and update ` window.YETT_BLACKLIST` or `window.YETT_WHITELIST` accordingly.
