### ISSUE TITLE
Feature request: block CSS

### ISSUE THREAD

**Issue by yoyurec** [elbywan/yett#51]
if there is anyway MutationObserver, why not to add CSS blocking? ))
with own black/white list...

**Comment by elbywan** [comment]
> if there is anyway MutationObserver, why not to add CSS blocking? ))

because this library is meant to be a lightweight way of blocking javascript scripts, not css/iframe/fonts/whatever

**Comment by Kristinita** [comment]
**Type: Question** :question:

### 1. Question

@elbywan, is any chance that similar behavior will be implemented for POST requests? If not, how to block unwanted third-party POST requests? I couldn’t find how to do this.

### 2. Example

For example, third-party scripts on my site send unwanted POST requests, which are blocked by uBlock Origin, AdBlock, Adblock Plus and others ad-blockers using [**Easylist filters**](https://easylist.to/):

![`/gen204?` Easylist filter](https://i.imgur.com/AplmB44.png)

![`/log?format=` Easylist filter](https://i.imgur.com/w8X8NJ8.png)

It would be nice if would be possible to block these requests like this:

```js
YETT_BLOCKLIST_POST_REQUESTS = [
	/\/log\?format=/,
	/\/gen204\?/
];
```

Thanks.
